<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mirepoix.AccessControl.Providers</RootNamespace>
    <AssemblyName>Mirepoix.AccessControl.Providers.SqlServer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mirepoix.AccessControl.Providers\Mirepoix.AccessControl.Providers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Providers.SqlServer.Tests" />
  </ItemGroup>
</Project>
