<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mirepoix.AccessControl.Core\Mirepoix.AccessControl.Core.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl.Engine\Mirepoix.AccessControl.Engine.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl.Protocol.Http\Mirepoix.AccessControl.Protocol.Http.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl.Providers.Client.Http\Mirepoix.AccessControl.Providers.Client.Http.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl.Providers.Server.Http\Mirepoix.AccessControl.Providers.Server.Http.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl\Mirepoix.AccessControl.csproj" />
  </ItemGroup>

</Project>
