<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mirepoix.AccessControl.Authorization.AspNetCore</RootNamespace>
    <AssemblyName>Mirepoix.AccessControl.Authorization.AspNetCore</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mirepoix.AccessControl.Engine\Mirepoix.AccessControl.Engine.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl.Providers\Mirepoix.AccessControl.Providers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Authorization.AspNetCore.Tests" />
  </ItemGroup>

</Project>
