<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mirepoix.AccessControl</RootNamespace>
    <AssemblyName>Mirepoix.AccessControl.Engine</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mirepoix.AccessControl\Mirepoix.AccessControl.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Engine.Tests" />
  </ItemGroup>
</Project>
