<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mirepoix.AccessControl.Management.Server.Http</RootNamespace>
    <AssemblyName>Mirepoix.AccessControl.Management.Server.Http</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mirepoix.AccessControl.Core\Mirepoix.AccessControl.Core.csproj" />
    <ProjectReference Include="..\Mirepoix.AccessControl.Management\Mirepoix.AccessControl.Management.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Management.Server.Http.Tests" />
  </ItemGroup>

</Project>
