<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mirepoix.AccessControl.Providers</RootNamespace>
    <AssemblyName>Mirepoix.AccessControl.Providers</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mirepoix.AccessControl.Engine\Mirepoix.AccessControl.Engine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Providers.SqlServer.Tests" />
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Providers.EntityFrameworkCore.Tests" />
    <InternalsVisibleTo Include="Mirepoix.AccessControl.Providers.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schema\Scripts\SqlServer\001_init.sql">
      <LogicalName>Mirepoix.AccessControl.Providers.Schema.Scripts.SqlServer.001_init.sql</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Schema\Scripts\PostgreSql\001_init.sql">
      <LogicalName>Mirepoix.AccessControl.Providers.Schema.Scripts.PostgreSql.001_init.sql</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
